---
linters-settings:
  # prevent import of "errors" instead of "github.com/pkg/errors"
  depguard:
    list-type: blacklist
    include-go-root: true
    packages:
      - errors

  lll:
    line-length: 140
    tab-width: 4

  unused:
    check-exported: false

  unparam:
    check-exported: true

  goimports:
    # put imports beginning with prefix after 3rd-party packages;
    # it's a comma-separated list of prefixes
    local-prefixes: github.com/Percona-Lab/mnogo_exporter

linters:
  enable-all: true
  disable:
      - lll
      - unused
      - testpackage
      - wsl 

issues:
  exclude-use-default: false
  exclude:
    # gas: Duplicated errcheck checks
    - 'G104: Errors unhandled'
  exclude-rules:
  - path: _test\.go
    linters:
    - unused
