version: "2"

linters:
  default: all
  enable:
    - gomodguard_v2
  disable:
    - exhaustruct
    - gochecknoglobals # we need globals for better performance, we use them for mapping, and we don't mutate them, so it's safe.
    - gomodguard # replaced by gomodguard_v2
    - lll
    - testpackage
    - varnamelen
    - wsl
    - wsl_v5
  settings:
    depguard:
      rules:
        main:
          deny:
            - pkg: "github.com/pkg/errors"
              desc: Use errors package
    unparam:
      check-exported: true
  exclusions:
    rules:
      # gosec G104: Errors unhandled
      - text: 'G104'
        linters:
          - gosec
      - path: _test\.go
        linters:
          - goconst

formatters:
  settings:
    goimports:
      local-prefixes:
        - github.com/percona/mongodb_exporter
