version: "2"

linters:
  default: all
  disable:
    - lll
    - testpackage
    - wsl
    - exhaustruct
    - varnamelen
    - gochecknoglobals # we need globals for better performance, we use them for mapping, and we don't mutate them, so it's safe.
    - wsl_v5
    - goconst # TODO: fix string literals duplication
    - tagalign # TODO: fix struct tags alignment
    - paralleltest # TODO: fix tests to be able to run in parallel
    - revive # TODO: fix revive linter issues
    - testifylint # TODO: fix testifylint issues
    - wrapcheck # TODO: fix wrapcheck issues
  settings:
    depguard:
      rules:
        main:
          deny:
            - pkg: "github.com/pkg/errors"
              desc: Use errors package
    unparam:
      check-exported: true
  exclusions:
    rules:
      # gosec G104: Errors unhandled
      - text: 'G104'
        linters:
          - gosec

formatters:
  settings:
    goimports:
      local-prefixes:
        - github.com/percona/mongodb_exporter
