dist: build
version: 2
builds:
  - binary: mongodb_exporter
    id: mongodb_exporter
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - 7
    ignore:
      - goos: darwin
        goarch: arm
    flags:
      - -v
    ldflags:
        - -s -w -X main.version=v{{.Version}} -X main.commit={{.ShortCommit}} -X main.buildDate={{.Date}}
archives:
  - name_template: "{{ .ProjectName }}-{{ .Version }}.{{ .Os }}-{{ .Arch }}"
    wrap_in_directory: true
snapshot:
  version_template: "{{ .ShortCommit }}"
changelog:
  use: github
release:
  github:
    owner: percona
    name: mongodb_exporter
  draft: true
  prerelease: auto
dockers_v2:
  - ids:
      - mongodb_exporter
    images:
      - docker.io/percona/mongodb_exporter
      - ghcr.io/percona/mongodb_exporter
    tags:
      - "{{.Major}}.{{.Minor}}"
      - "{{.Version}}"
    dockerfile: Dockerfile
    platforms:
      - linux/amd64
      - linux/arm64
    flags:
      - "--pull"

nfpms:
  - file_name_template: "{{ .ProjectName }}-{{ .Version }}.{{ .Os }}-{{- if eq .Arch `amd64` }}64-bit{{- else }}{{ .Arch }}{{ end }}"
    homepage:  https://www.percona.com/
    description: MongoDB exporter for Prometheus
    maintainer: Percona
    vendor: Percona
    license: Apache 2.0
    formats:
    - deb
    - rpm
    bindir: /usr/bin
    scripts:
      postinstall: ".scripts/postinst"
    contents:
      - src: .scripts/systemd/mongodb_exporter.service
        dst: /etc/systemd/system/mongodb_exporter.service
        type: "config|noreplace"
      - src: .scripts/default/mongodb_exporter.example
        dst: /etc/default/mongodb_exporter.example
      - src: LICENSE
        dst: /usr/share/doc/mongodb_exporter/LICENSE
