#!/bin/sh

set -e

echo "Creating user and group..."

useradd --system \
        --no-create-home \
        --shell /sbin/nologin \
        --comment "MongoDB Exporter" \
        mongodb_exporter

systemctl --system daemon-reload >/dev/null || true

exit 0
