name: Lint

on:
  push:
    branches:
      - main
    tags:
      - v[0-9]+.[0-9]+.[0-9]+*
  pull_request:

permissions:
  contents: read

jobs:
  lint:
    name: Lint Check

    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up Go
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        with:
          go-version-file: ${{ github.workspace }}/go.mod

      - name: Initialize dependencies and linters
        run: make init

      - name: Diff
        run: |
          make format
          git diff --exit-code

      - name: Run code linters
        uses: reviewdog/action-golangci-lint@c76cceaaab89abe74e649d2e34c6c9adc26662d2 # v2.10.0
        with:
          go_version_file: ${{ github.workspace }}/go.mod
          reporter: github-pr-review
          fail_level: error
          filter_mode: added
          cache: false
          golangci_lint_flags: "--config=.golangci.yml"
          golangci_lint_version: v2.12.2

      - name: Run license check
        run: |
          make check-license
