name: Lint

on:
  push:
    branches:
      - main
    tags:
      - v[0-9]+.[0-9]+.[0-9]+*
  pull_request:

permissions:
  contents: read

jobs:
  lint:
    name: Lint Check

    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Set up Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: ${{ github.workspace }}/go.mod

      - name: Initialize dependencies and linters
        run: make init

      - name: Diff
        run: |
          make format
          git diff --exit-code

      - name: Run code linters
        uses: reviewdog/action-golangci-lint@c76cceaaab89abe74e649d2e34c6c9adc26662d2 # v2.10.0
        with:
          go_version_file: ${{ github.workspace }}/go.mod
          reporter: github-pr-review
          fail_level: error
          filter_mode: added
          cache: false
          golangci_lint_flags: "--config=.golangci.yml"
          golangci_lint_version: v2.13.1

      - name: Run license check
        run: |
          make check-license
